### ISSUE TITLE
While using the Python Engine, can I create and embed plots in my document?

### ISSUE THREAD

**Issue by soumendra** [yihui/knitr-examples#49]
matplotlib plots don't seem to be working.

**Comment by yihui** [comment]
No, it won't work. Currently the python engine is basically `python -c command`, and there is nothing fancy (plots won't be automatically captured, and you have to manually save them to files, then include them).

**Comment by soumendra** [comment]
Thanks. closing the issue then, since you didn't mention the feature was in the works :)

**Comment by yihui** [comment]
Thanks for your understanding. This might be improved in the future, although it is unlikely to be my top priority.
