### ISSUE TITLE
Zero-width space in 065-rmd-chunk.Rmd

### ISSUE THREAD

**Issue by pschloss** [yihui/knitr-examples#52]
Thanks for providing the example for how to use a zero-width space to show the full code chunk from `&#8203;``{r} to ```.  I think this should be documented somewhere, but if someone were to copy and paste the code chunk into a text editor (other than RStudio) and then run it through knitr, they will get an error that is not entirely helpful.

		---
		output: html_document
		---

		```{r test}
		x <- runif(5)
		x2 <- sum(x^2)
		`​``

		This is a test. The sum of x squared is `r x2`

The output error message looks like so...

```
> render('test.Rmd')

processing file: test.Rmd
  |................................                                 |  50%
  ordinary text without R code

  |.................................................................| 100%
label: test
Quitting from lines 6-10 (test.Rmd) 
Error in parse(text = x, srcfile = src) : <text>:3:6: unexpected symbol
4: 
5: This is a test. The sum of x squared is `
        ^
Calls: render ... evaluate -> parse_all -> parse_all.character -> parse

Execution halted
```

The solution is to remove the zero-width space between the first and second back ticks in the closing ` ``` `. I don't know that this is a bug with the example so much as something that should be documented and I found confusing when I was teaching this past week.

**Comment by yihui** [comment]
The example 065 used a zero-width space in the opening instead of the closing ```` ``` ````:

![image](https://cloud.githubusercontent.com/assets/163582/23617418/ae1f0964-0252-11e7-995a-a9627602e133.png)

I don't know how you ended up with a space in the closing ```` ``` ````.

**Comment by pschloss** [comment]
Sorry. There would still be a copy/paste error, however if the zero-width space was in the opening.

Pat

**Comment by yihui** [comment]
I guess FAQ 7 should be clear enough: https://yihui.name/knitr/faq/
