### ISSUE TITLE
engine bash not work on windows OS

### ISSUE THREAD

**Issue by Scelta** [yihui/knitr-examples#56]
Refer to [027-engine-bash.Rmd](https://github.com/yihui/knitr-examples/blob/9eff56edb0c8294b612e68c629c79a9ba0dfb5b1/027-engine-bash.Rmd)
 I've set PATH to make sure:

````
```{r}
>Sys.which('bash')
                         bash 
"D:\\cygwin64\\bin\\bash.exe" 
```
````

Then still get error when I try to run a bash command in R:

````
```{bash}
echo hello world
echo 'a b c' | sed 's/ /\|/g'
```
````

```
bash: C:\Users\MyName\AppData\Local\Temp\Rtmpao1Io3\chunk-code4aa837efa03.: No such file or directory
```

I use `knitr 1.17`, and R version information below:

```
> version
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          3.3                         
year           2017                        
month          03                          
day            06                          
svn rev        72310                       
language       R                           
version.string R version 3.3.3 (2017-03-06)
nickname       Another Canoe     
```

Does the knitr direct to a worng path? How can I avoid this error. Thanks!

**Comment by yihui** [comment]
The error message looks weird to me. knitr does not write the bash code to a file before executing it. How exactly did you compile this document? I feel you might be using R Markdown Notebooks.

**Comment by Scelta** [comment]
Yes, but then I tried md_document, html_codcument, word_document and ioslides_presentation, none of them worked. Below shows the minimal Rmd file to generate my error.

    ---
    title: "process"
    output: md_document
    ---
    ```{bash} 
    echo hello world
    echo 'a b c' | sed 's/ /\|/g'
    ```
```
bash: C:\Users\MyName\AppData\Local\Temp\RtmpmouNnD\chunk-code46b81ccd775f.: No such file or directory
```
And I can see nothing newly produced in the RtmpmouNnD directory.

**Comment by yihui** [comment]
You didn't actually answer my question: how exactly did you compile this document? The Knit button on the RStudio IDE toolbar? Command-line? The toolbar above the code chunk? I wouldn't expect the last approach to work.

**Comment by Scelta** [comment]
Now I understand. The error occurred when I click 'run' button on the Studio IDE toolbar.

Command-line or type `render(input="README.Rmd")` in Studio both work well.

**Comment by yihui** [comment]
Okay. This issue belongs to the RStudio IDE and R Markdown Notebooks, so support.rstudio.com may be a better place to report it. Thanks!

**Comment by kevinushey** [comment]
@Scelta: do you see this same issue in the [RStudio preview release](https://www.rstudio.com/products/rstudio/download/preview/)?

**Comment by kevinushey** [comment]
I've reproduced the issue there; it is indeed an RStudio issue and we'll try to dig in further!
