### ISSUE TITLE
Messages with false appendLF still gets seperated

### ISSUE THREAD

**Issue by EmilRehnberg** [yihui/knitr-examples#58]
I cloned the repo and executed `./knitall` but the output for the `117-messages.md` differs from the output in the repo in that the messages are separated even though the `appendLF` flag is set to `FALSE`.

Any idea as to what is the cause of this?

```
R version 3.4.1 (2017-06-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: OS X El Capitan 10.11.6
```

## Output from the last 20 lines.

A message in `message(..., appendLF = FALSE)` will be merged with the next adjacent message:

```r
f3 = function() {
    message("Hello ", appendLF = FALSE)
    message("World!")
}
f3()
```

```
## Hello
```

```
## World!
```

**Comment by yihui** [comment]
I cannot reproduce your issue. [Is everything up-to-date?](https://yihui.name/en/2017/05/when-in-doubt-upgrade/) e.g. `update.packages(ask = FALSE, checkBuilt = TRUE)`
