### ISSUE TITLE
Integration tests still valid ? 

### ISSUE THREAD

**Issue by cderv** [yihui/knitr-examples#72]
Are the integration tests on branch still valid ? 
https://github.com/yihui/knitr-examples#integration-tests

Following changes in knitr
https://github.com/yihui/knitr/commit/16493ec1862bddfa66f7288c7ad2a22a76d51e08#diff-6ac3f79fc25d95cd1e3d51da53a4b21b939437392578a35ae8cd6d5366ca5485

I am not so sure this is possible to create a branch in a fork to get the test done. 
It seems integration will happen only on master now. Example in one of the last travis jobs:
https://travis-ci.com/github/yihui/knitr/jobs/421565801

I think we won't be needed that at the examples will be checked for each PR (following https://github.com/yihui/knitr/pull/1920), but we would still need a mechanism for someone to add a tests in knitr-examples and have it check when doing a knitr PR. 

This issue is

* To remind to update the README
* Or adjust our CI worflow to make what is describe works again

**Comment by cderv** [comment]
@yihui related to the PR you merged and knitr's one. 

Know that the integration tests describe won't work anymore, but as explained above I don't think it was still working recently in Travis.

**Comment by yihui** [comment]
> It seems integration will happen only on master now.

That's correct. I'll remove that section in readme. Thanks!
