### ISSUE TITLE
Modifying powerpoint templates on Windows results on corrupt pptx file, aka "Powerpoint found a problem"

### ISSUE THREAD

**Issue by JanaJarecki** [yihui/knitr-examples#89]
Hi,

this concerns using a custom powerpoint template. Steps to reproduce
  - run the below rmd WITHOUT the reference_doc
  - save the powerpoint as "test-template - Copy.pptx" and in the master for master layout 2 in the menu "Slide Master" uncheck the box "Footer"
  - re-run it WITH the reference doc
 
This results in a corrupted pptx with the error "Powerpoint found a problem with content in ...".

# OS
Edition	Windows 10 Business
OS build	19045.3448

# sessionInfo
R version 4.3.0 (2023-04-21 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

# Example Code

    ---
    title: Results
    author: Rewoso
    date: "`r format(Sys.time(), '%d/%m/%y')`"
    output: 
      officedown::rpptx_document:
        reference_doc: test-template - Copy.pptx
    editor_options: 
      chunk_output_type: console
    ---
    
    
    
    ```{r, setup, echo=0, warning=0, message=0}
    pacman::p_load(ggplot2)
    knitr::opts_chunk$set(
      results = "asis",
      echo = FALSE,
      warning = FALSE,
      error = FALSE,
      message = FALSE
    )
    ```
    
    ## Test
    
    ```{r, fig.width=10, fig.height=4}
       ggplot(iris) + geom_histogram(aes(Sepal.Length))
    ```

**Comment by cderv** [comment]
I am on windows and I can't reproduce this unfortunately. 

Can you send me the pptx you are generating ? 

Are you modifying it with Powerpoint or another tool ?

**Comment by JanaJarecki** [comment]
Hi,

yes sure, attache example-master.pptx.

Actually here's what caused the issue: 

- going to the Master
- then to slide "Title Slide" (2)
- then under the menu _Slide Master_ unchecking the [  ] Footer option (which by default is checked).

Attached is the ppt that results in the corruption

I edited the issue to be truthful

Does the issue make sense? It may be that powerpoint is re-numbering or re-naming the elements in the xml file when the box [  ] Footer is un-checked...

Jana

[example-master.pptx](https://github.com/yihui/knitr-examples/files/12906172/example-master.pptx)

**Comment by cderv** [comment]
Thanks for the detailed report. I think you found an issue with Pandoc, when `date` field is present. 
If you remove the `date` in your YAML it should work correctly.

**Comment by cderv** [comment]
I opened an issue upstream to track 
* https://github.com/jgm/pandoc/issues/9139

Thanks for the report!

**Comment by JanaJarecki** [comment]
Thank you for the patience and the initiative! Be well ;)
