### ISSUE TITLE
Change in highlighting ? 

### ISSUE THREAD

**Issue by cderv** [yihui/knitr-examples#92]
It seems something made 098- example fails 
https://github.com/yihui/knitr/actions/runs/11182870663/job/31090124159

We should fix to remove CI error on **knitr**

**Comment by yihui** [comment]
Thanks! I think I have fixed it: https://github.com/yihui/knitr-examples/commit/14b81d78e8359da93002b598b0b59d23c936d665

**Comment by cderv** [comment]
Oh missed it. It means we just need to trigger CI again. I'll do that. Thanks !

**Comment by yihui** [comment]
Yes, I forgot to re-run CI in the knitr repo.
